projeto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path

from recipes import views

app_name = 'recipes'

urlpatterns = [
    path('', views.index, name='index'),
    path('recipes/category/<int:category_id>/', views.category, name='category'),
    path('recipes/<int:id>/', views.recipes, name='recipes'),
]

recipes/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name

class Recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField()
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=65)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to='recipes/covers/%Y/%m/%d/', blank=True, default='')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, default=None)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title
    

recipes/views.py
from django.http import HttpResponse
from django.shortcuts import render

from recipes.models import Recipe
from utils.recipes.factory import make_recipe


# Create your views here.
def index(request):
    recipes = Recipe.objects.filter(is_published=True).order_by('-id')
    return render(request, 'recipes/pages/index.html', context={
        'recipes': recipes
    })

def category(request, category_id):
    recipes = Recipe.objects.filter(category__id=category_id, is_published=True).order_by('-id')
    return render(request, 'recipes/pages/category.html', context={
        'recipes': recipes
    })

def recipes(request, id):
    return render(request, 'recipes/pages/recipes-views.html', context={
        'recipe': make_recipe(),
        'is_detail_page': True
    })

recipes/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>

    <h1>HOME</h1>
    
</body>
</html>

recipes/templates/recipes/pages/category.html
{% extends "global/base.html" %}

{% block title %}Category{% endblock title %}

{% block content %}
<div class="main-content main-content-list container">

    {% for recipe in recipes %}
        {% include "recipes/partials/recipe.html" %}
    {% endfor %}

</div>
{% endblock content %}

recipes/templates/recipes/pages/index.html
{% extends "global/base.html" %}

{% block title %}Home - Recipes{% endblock title %}

{% block content %}
<div class="main-content main-content-list container">

    {% for recipe in recipes %}
        {% include "recipes/partials/recipe.html" %}
    {% endfor %}

</div>
{% endblock content %}

recipes/templates/recipes/pages/recipes-views.html
{% extends "global/base.html" %}

{% block title %}Recipes{% endblock title %}

{% block content %}
<div class="main-content main-content-detail container">

    {% include "recipes/partials/recipe.html" %}

</div>
{% endblock content %}

recipes/templates/recipes/partials/footer.html
<footer class="main-footer">
    <div class="developer">
      <a href="https://carreirafernando.github.io/" target="_blank" rel="noreferrer noopener">By Fernando Carreira</a>
    </div>
    <div class="powered">
      <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Powered by Django</a>
    </div>
</footer>

recipes/templates/recipes/partials/head.html
{% load static %}

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<script src="https://kit.fontawesome.com/16018fdfba.js" crossorigin="anonymous"></script>

<!-- Gloogle Fontes -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">

<link rel="stylesheet" href="{% static 'recipes/css/style.css' %}">
    

recipes/templates/recipes/partials/header.html
<header class="main-header-container">
    <div class="main-header container">
        <h1>
            <a class="main-logo" href="{% url 'recipes:index' %}">
                <i class="fa-solid fa-utensils main-logo-icon"></i>
                <span class="main-logo-text">Recipes</span>
            </a>
        </h1>
    </div>
</header>

recipes/templates/recipes/partials/recipe.html
<div class="recipe recipe-list-item">

    {% if recipe.cover %}
        <div class="recipe-cover">
            <a href="{% url 'recipes:recipes' recipe.id %}">
                <img src="{{ recipe.cover.url }}" alt="Temporario">
            </a>
        </div>
    {% endif %}
    

    <div class="recipe-title-container">
        <a href="{% url 'recipes:recipes' recipe.id %}">
            <h2 class="recipe-title">
                {{ recipe.title }}
            </h2>
        </a>
    </div>

    <div class="recipe-author">
        <span class="recipe-author-item">
            <i class="fas fa-user"></i>
            {% if recipe.author.first_name %}
                {{ recipe.author.first_name }} {{ recipe.author.last_name }}
            {% else %}
                {{ recipe.author.username }}
            {% endif %}
        </span>
        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{ recipe.created_at }}
        </span>

        {% if recipe.category is not None %}
            <span class="recipe-author-item">
                <a href="{% url 'recipes:category' recipe.category.id %}">
                    <i class="fas fa-layer-group"></i>
                    <span>{{ recipe.category.name }}</span>
                </a>
            </span>
        {% endif %}

    </div>

    {% if is_detail_page is not True %}
        <div class="recipe-content">
            <p>
                {{ recipe.description }}
            </p>
        </div>
    {% else %}
    <div class="recipe-content">
        <p>
            {{ recipe.preparation_steps|linebreaksbr }}
        </p>
    </div>
    {% endif %}

    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Preparo</h3>
            <div class="recipe-meta-text">
                {{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}
            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> Porções</h3>
            <div class="recipe-meta-text">
                {{ recipe.servings }} {{ recipe.servings_unit }}
            </div>
        </div>
    </div>

    {% if is_detail_page is not True %}
        <footer class="recipe-footer">
            <a class="recipe-read-more button button-dark button-full-width" href="{% url 'recipes:recipes' recipe.id %}">
                <i class="fas fa-eye"></i>
                <span>ver mais...</span>
            </a>
        </footer>
    {% endif %}
    

</div>

recipes/templates/recipes/partials/search.html
<div class="search-container">
    <div class="container">
        <form action="" class="search-form">
            <input type="search" class="search-input" name="search">
            <button type="submit" class="search-button">
                <i class="fa-solid fa-magnifying-glass"></i>
            </button>
        </form>
    </div>
</div>